name: Release

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Minecraft version
        run: |
          cat version.txt
          echo "ver=$(<version.txt)" >> "$GITHUB_ENV"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: key_language_pack.zip
          name: "${{ env.ver }}"
          tag_name: "${{ env.ver }}"