name: Release

on:
  push:
    paths:
      - '**.zip'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Minecraft version
        run: |
          cat version.txt
          echo "ver=$(<version.txt)" >> "$GITHUB_ENV"

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.ver }}"
          title: "${{ env.ver }}"
          prerelease: false
          files: |
            key_language_pack.zip