name: Update resource pack

on:
  schedule:
    - cron: "30 16 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update language files
        run: python source.py

      - name: Update resource pack
        run: python pack.py

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Update language files"

      - name: Get Minecraft version
        run: |
          cat version.txt
          echo "ver=$(<version.txt)" >> "$GITHUB_ENV"

      - name: Release
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tag: "${{ env.ver }}"
          files: key_language_pack.zip
          name: "${{ env.ver }}"
          version: "${{ env.ver }}"
